[package]
name = "pca"
version = "0.1.0"
description = "Verifiable Principal Component Analysis"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "v0.1.7" }

[scripts]
test = "scarb cairo-test -f pca_test"