[package]
name = "lagrange"
version = "0.1.0"
description = "Verifiable Lagrange Interpolation"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "v0.1.9" }

[scripts]
test = "scarb cairo-test -f lagrange_test"