[package]
name = "multiple_linear_regresion"
version = "0.1.0"


[dependencies]
orion = { git = "https://github.com/gizatechxyz/onnx-cairo" }

[scripts]
test = "scarb cairo-test -f multiple_linear_regression_test"