
    [package]
    name = "sequential_1_dense_2_matmul_readvariableop_0"
    version = "0.1.0"

    [dependencies]
    orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "v0.1.5" }
    