[package]
name = "verifiable_support_vector_machine"
version = "0.1.0"

[dependencies]
starknet = ">=2.1.1"
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "v0.1.1" }

[scripts]
test = "scarb cairo-test -f svm_test"
